variables:
  GIT_STRATEGY: clone
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  SERVICE_NAME: "myservice"
  DOCKER_REGISTRY_HOST: "<your-docker-registry>"

image: docker:stable
services:
  - name: docker:dind
    command: ["--insecure-registry=<your-docker-registry>"]
    
before_script:
  - echo "192.168.4.139 <your-docker-registry>" >> /etc/hosts
  - apk add git && cd $CI_PROJECT_DIR && export TAG=$(git describe --tags --abbrev=0)
  - echo $CI_PROJECT_DIR && echo $TAG && echo $CI_COMMIT_REF_NAME && echo $CI_COMMIT_SHORT_SHA

stages:
  - build
  - test
  - deploy
    
# 開發中的需求
build_image:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY_HOST/$SERVICE_NAME:$TAG\_$CI_COMMIT_REF_NAME\_$CI_COMMIT_SHORT_SHA .
    - docker login -u $HARBOR_USER -p $HARBOR_PWD $DOCKER_REGISTRY_HOST
    - docker push $DOCKER_REGISTRY_HOST/$SERVICE_NAME:$TAG\_$CI_COMMIT_REF_NAME\_$CI_COMMIT_SHORT_SHA
  only:
    - /^f[0-9]{5}$/

# 已經合併回主分支的功能，只需要打tag就能自動執行
master_build_image:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY_HOST/$SERVICE_NAME:$CI_COMMIT_REF_NAME .
    - docker login -u $HARBOR_USER -p $HARBOR_PWD $DOCKER_REGISTRY_HOST
    - docker push $DOCKER_REGISTRY_HOST/$SERVICE_NAME:$CI_COMMIT_REF_NAME
  only:
    - tags

# 開發中的需求
test_image:
  stage: test
  script:
    - echo "test passed"
  only:
    - /^f[0-9]{5}$/

# 開發中的需求
notify:
  stage: deploy
  script:
    - apk add curl
    - curl -X POST http://192.168.4.141:8080/job/Webhook/build?token=asdfqwer --user xxx:ooo --data-urlencode json="{\"parameter\":[{\"name\":\"tag\", \"value\":\"$TAG\_$CI_COMMIT_REF_NAME\_$CI_COMMIT_SHORT_SHA\"}]}"
  only:
    - /^f[0-9]{5}$/

# 已經合併回主分支的功能，只需要打tag就能自動執行
master_notify:
  stage: deploy
  script:
    - apk add curl
    - curl -X POST http://192.168.4.141:8080/job/Webhook/build?token=asdfqwer --user xxx:ooo --data-urlencode json="{\"parameter\":[{\"name\":\"tag\", \"value\":\"$CI_COMMIT_REF_NAME\"}]}"
  environment: dev
  only:
    - tags
