apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://192.168.4.71:30080/"
      token = "P-kqby1VbzjyUDfkUZwj"
      executor = "kubernetes"
      clone_url = "http://svc-gitlab"
      [runners.kubernetes]
        namespace = "default"
        image = "alpine:latest"
        privileged = true
        disable_cache = true
