apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "<gitlab_host>"
      token = "<response_token_from_step1>"
      executor = "kubernetes"
      clone_url = "http://svc-gitlab"
      [runners.kubernetes]
        namespace = "default"
        image = "alpine:latest"
        privileged = true
        disable_cache = true
