apiVersion: v1
kind: ConfigMap
metadata:
  namespace: john
  name: cfg-gitlab-runner
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://<gitlab_url>/"
      token = "xxxxx""
      executor = "kubernetes"
      clone_url = "http://svc-gitlab"
      [runners.kubernetes]
        namespace = "john"
        image = "alpine:latest"
        privileged = true
        disable_cache = true
