apiVersion: v1
kind: Service
metadata:
  name: svc-gitlab
  labels:
    svc: gitlab
spec:
  type: NodePort
  ports:
    - name: "https"
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: "ssh"
      port: 22
      targetPort: 22
      nodePort: 30022
  selector:
    test: gitlab