apiVersion: v1
kind: Service
metadata:
  namespace: john
  name: svc-cidemo
  labels:
    svc: cidemo
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 9090
      targetPort: 9090
      nodePort: 30909
  selector:
    app: cidemo