apiVersion: v1
kind: Service
metadata:
  namespace: john
  name: svc-gitlab
  labels:
    svc: gitlab
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    test: gitlab